# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

project 'Demo-iOS.xcodeproj'

target 'Demo-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Use the local podspec instead of the main one
  pod 'MPVKit-Local', :podspec => './LocalPods/MPVKit-Local.podspec'
end
